const theme = {
    ltr: "text-left",
    rtl: "text-right",
    paragraph: "mb-2 text-base leading-relaxed ",
    quote: "pl-4 border-l-4 border-gray-300 text-gray-500 italic",
    heading: {
        h1: "text-4xl  my-4",
        h2: "text-3xl  my-4",
        h3: "text-2xl  my-3",
        h4: "text-xl  my-2",
        h5: "text-lg  my-1",
        h6: "text-base font-medium",
    },
    list: {
        checklist: "relative px-[30px] mx-[12px] list-none outline-none",
        listitemChecked: "relative px-[30px] mx-[12px] list-none line-through outline-none",
        listitemUnchecked: "relative px-[30px] mx-[12px] list-none outline-none",
        nested: {
            listitem: "list-none",
        },
        ol: "max-w-md space-y-1 list-decimal list-inside",
        ul: "max-w-md space-y-1 list-disc list-inside",
        listitem: "mx-8",
    },
    hashtag: "text-blue-600 dark:text-blue-400 font-medium",
    image: "max-w-full rounded-lg shadow-md my-4",
    link: "text-blue-600 hover:text-blue-800 underline cursor-pointer dark:text-blue-400 dark:hover:text-blue-300",
    text: {
        bold: "font-bold",
        code: "bg-gray-100 dark:bg-gray-800 px-1 py-0.5 rounded text-sm font-mono",
        italic: "italic",
        strikethrough: "line-through",
        subscript: "align-sub text-xs",
        superscript: "align-super text-xs",
        underline: "underline",
        underlineStrikethrough: "underline line-through",
        uppercase: "uppercase",
        lowercase: "lowercase",
        capitalize: "capitalize",
        highlight: "bg-yellow-200",
    },
    code: "bg-gray-100 dark:bg-gray-800 text-sm p-2 rounded font-mono overflow-x-auto",
    codeHighlight: {
        atrule: "text-purple-500",
        attr: "text-orange-500",
        boolean: "text-green-600",
        builtin: "text-indigo-500",
        cdata: "text-gray-400 italic",
        char: "text-indigo-400",
        class: "text-blue-600",
        "class-name": "text-blue-500",
        comment: "text-gray-500 italic",
        constant: "text-green-500",
        deleted: "bg-red-100 text-red-600 line-through",
        doctype: "text-gray-500 italic",
        entity: "text-pink-500",
        function: "text-indigo-600",
        important: "text-red-600 font-bold",
        inserted: "bg-green-100 text-green-600",
        keyword: "text-purple-600",
        namespace: "text-pink-600",
        number: "text-green-700",
        operator: "text-pink-500",
        prolog: "text-gray-500 italic",
        property: "text-teal-600",
        punctuation: "text-gray-500",
        regex: "text-red-500",
        selector: "text-blue-600",
        string: "text-green-600",
        symbol: "text-purple-500",
        tag: "text-red-600",
        url: "text-blue-400 underline",
        variable: "text-orange-600",
    },
};

export default theme;