export const main_ario_cu = "https://cu.ardrive.io/dry-run?process-id=qNvAoz0TgcH7DMg8BCVn8jF32QH5L6T29VjHxhHqqGE"
export const ario_cu = "https://cu.ardrive.io/dry-run?process-id="
// export const process = "yGHJoGqju9njoiIYCPuHo7ZXqch2_uY6i0HGg7af3Og"
export const process = "izkJ6WCgKA4ncfB7IA7fcAde3lHlX64vxebRWeNRWt0"
export const arns = "qNvAoz0TgcH7DMg8BCVn8jF32QH5L6T29VjHxhHqqGE"